function pos = forward_kin(a1,a2,a3,a4,a5,t1,t2,t3,t4)
%FORWARD_KIN
%    POS = FORWARD_KIN(A1,A2,A3,A4,A5,T1,T2,T3,T4)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    17-Jun-2024 10:31:15

t6 = cos(t1);
t7 = cos(t2);
t8 = cos(t3);
t9 = cos(t4);
t10 = sin(t1);
t11 = sin(t2);
t12 = sin(t3);
t13 = sin(t4);
t14 = a1+a2;
t15 = a3+t14;
t16 = a1.*t10;
t17 = t6.*t7;
t18 = t6.*t11;
t19 = t7.*t10;
t20 = t10.*t11;
t21 = t6-1.0;
t22 = t7-1.0;
t23 = t8-1.0;
t24 = t9-1.0;
t25 = a4+t15;
t27 = -t20;
t28 = a1.*t21;
t29 = t14.*t18;
t30 = t14.*t20;
t32 = t6.*t14.*t22;
t33 = t18+t19;
t34 = t10.*t14.*t22;
t26 = a5+t25;
t31 = -t28;
t35 = -t32;
t36 = t17+t27;
t37 = t8.*t33;
t38 = t12.*t33;
t44 = t15.*t23.*t33;
t39 = t8.*t36;
t40 = t12.*t36;
t41 = -t38;
t42 = t15.*t38;
t45 = t15.*t23.*t36;
t43 = t15.*t40;
t46 = -t45;
t47 = t37+t40;
t48 = t39+t41;
pos = reshape([0.0,a1,0.0,t16-t10.*t14,t31+t6.*t14,0.0,t16+t29+t34-t15.*t33,t30+t31+t35+t15.*t36,0.0,t16+t29+t34+t43+t44-t25.*t47,t30+t31+t35+t42+t46-t25.*(t38-t39),0.0,t16+t29+t34+t43+t44-t26.*(t9.*t47-t13.*(t38-t39))+t24.*t25.*t47-t13.*t25.*(t38-t39),t30+t31+t35+t42+t46-t26.*(t13.*t47+t9.*(t38-t39))+t13.*t25.*t47+t24.*t25.*(t38-t39),0.0],[3,5]);
