function [fitresult, gof] = createFit(x_pos, y_pos)
%CREATEFIT(X_POS,Y_POS)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x_pos
%      Y Output: y_pos
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Mar-2023 16:12:28


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x_pos, y_pos );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% % Plot fit with data.
% figure( 'Name', 'untitled fit 1' );

% h = plot( fitresult, xData, yData );
% axis([1,640,1,480]);
% legend( h, 'y_pos vs. x_pos', 'untitled fit 1', 'Location', 'NorthEast', 'Interpreter', 'none' );
% % Label axes
% xlabel( 'x_pos', 'Interpreter', 'none' );
% ylabel( 'y_pos', 'Interpreter', 'none' );
% grid on


